### PR TITLE
typos and mysing use statement.

### PR DESCRIPTION
**Pull request by Faryshta**

### CODE REVIEW

**Comment by raoul2000** [comment]
thanks
I will check that as soon as possible

**Comment by RustemS** [comment]
Hello! it works , but when you come in to your account , that's such a poser , why so ? Navbar zasshiryaetsya . Tried in the base , everything is fine, but in advanced so?
Please help me . Submit a screenshot to you in the mail. I'm sorry that I write here .

**Comment by raoul2000** [comment]
the problem doesn't come from your changes but from the CI.. I will check that when I have time.
Thank you

**Comment by RustemS** [comment]
Как определить ошибку, пожалуйста, дайте мне знать. Спасибо.

2016-06-21 3:26 GMT+06:00 raoul <notifications@github.com>:

**Comment by RustemS** [comment]
Как определить ошибку, пожалуйста, дайте мне знать. Спасибо.


2016-06-23 18:50 GMT+06:00 Rustem Sabitov <sabitovrk@gmail.com>:

**Comment by RustemS** [comment]
How to define an error, please let me know . Thank you.


2016-06-23 18:52 GMT+06:00 Rustem Sabitov <sabitovrk@gmail.com>:

**Pull request merged**
